authapp/urls.py
from django.urls import path

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('profile/', authapp.profile, name='profile'),
]

datescontrol/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),

    path('', include('mainapp.urls', namespace='main')),
    path('itemtypes/', include('itemtypesapp.urls', namespace='itemtypes')),
    path('workers/', include('workersapp.urls', namespace='workers')),
    path('auth/', include('authapp.urls', namespace='auth')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path

import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.index, name='index'),
    path('items/', mainapp.items, name='items'),
    path('items/city_filter/<int:city_pk>/', mainapp.city_filter, name='city_filter'),
    path('items/company_filter/<int:company_pk>/', mainapp.company_filter, name='company_filter'),
    path('items/departament_filter/<int:departament_pk>/', mainapp.departament_filter, name='departament_filter'),
    path('items/brig_filter/<int:brig_pk>/', mainapp.brig_filter, name='brig_filter'),
    path('items/worker_filter/<int:worker_pk>', mainapp.worker_filter, name='worker_filter'),
    path('items/group_filter/<int:item_group_pk>', mainapp.group_filter, name='group_filter'),
    path('items/type_filter/<int:item_type_pk>', mainapp.type_filter, name='type_filter'),
]

workersapp/urls.py
from django.urls import path

import workersapp.views as workersapp

app_name = 'workersapp'

urlpatterns = [
    path('', workersapp.workers, name='index'),
    path('city_filter/<int:city_pk>/', workersapp.city_filter, name='city_filter'),
    path('company_filter/<int:company_pk>/', workersapp.company_filter, name='company_filter'),
    path('departament_filter/<int:departament_pk>/', workersapp.departament_filter, name='departament_filter'),
    path('brig_filter/<int:brig_pk>/', workersapp.brig_filter, name='brig_filter'),
    path('info/<int:pk>/', workersapp.info, name='info'),
]

mainapp/models.py
from datetime import date, datetime
from calendar import monthrange

from django.db import models

from itemtypesapp.models import ItemTypeModel
from workersapp.models import WorkerModel


# Create your models here.
class ItemModel(models.Model):
    worker = models.ForeignKey(WorkerModel, on_delete=models.CASCADE)
    item_type = models.ForeignKey(ItemTypeModel, on_delete=models.CASCADE)
    description = models.TextField('Примечание', blank=True)
    inventory_number = models.CharField('Инвентарный номер', max_length=64, blank=True)
    change_for = models.DateField('Дата выдачи', blank=True)
    test_for = models.DateField('Дата проверки')
    is_active = models.BooleanField('Активен', default=True)

    def __str__(self):
        return f'{self.item_type.name}-{self.inventory_number} ({self.worker.name})'

    @property
    def test_to(self):
        return add_months(self.test_for, self.item_type.test_interval)

    @property
    def change_to(self):
        return add_months(self.change_for, self.item_type.change_interval)

    @property
    def elapse(self):
        is_doc = self.item_type.group.doc_or_tool == 'Удостоверение'
        return min(self.test_to, self.change_to) if is_doc else self.test_to

    @property
    def delta(self):
        next_test = self.elapse
        today = datetime.now()
        today = date(today.year, today.month, today.day)
        return (next_test - today).days

    @property
    def status(self):
        delta = self.delta
        if delta > 90:
            return 0
        elif delta > 30:
            return 1
        elif delta > 0:
            return 2
        else:
            return 3

    class Meta:
        verbose_name = 'Предмет'
        verbose_name_plural = 'Предметы'
        ordering = ['worker']


def add_months(source_date, months):
    month = source_date.month - 1 + months
    year = source_date.year + month // 12
    month = month % 12 + 1
    day = min(source_date.day, monthrange(year, month)[1])
    return date(year, month, day)

mainapp/views.py
from datetime import date, timedelta, datetime

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse

from mainapp.models import ItemModel
from itemtypesapp.models import ItemTypeModel
from workersapp.models import WorkerModel, CityModel, CompanyModel, DepartamentModel


def index(request):
    context = {'page_title': 'стартовая'}
    return render(request, 'mainapp/index.html', context)


@login_required
def items(request):
    linked_check = is_linked(request)
    if linked_check:
        return linked_check
    return get_items_response(request)


@login_required
def group_filter(request, item_group_pk):
    linked_check = is_linked(request)
    if linked_check:
        return linked_check
    items_list = ItemModel.objects.filter(item_type__group_id=item_group_pk)
    return get_items_response(request, gived_items=items_list)


@login_required
def type_filter(request, item_type_pk):
    linked_check = is_linked(request)
    if linked_check:
        return linked_check
    items_list = ItemModel.objects.filter(item_type_id=item_type_pk)
    return get_items_response(request, gived_items=items_list)


@login_required
def city_filter(request, city_pk):
    linked_check = is_linked(request)
    if linked_check:
        return linked_check
    detail = 'City'
    workers = get_object_or_404(CityModel, pk=city_pk).workers()
    return get_items_response(request, workers, detail)


@login_required
def company_filter(request, company_pk):
    linked_check = is_linked(request)
    if linked_check:
        return linked_check
    detail = 'Company'
    workers = get_object_or_404(CompanyModel, pk=company_pk).workers()
    return get_items_response(request, workers, detail)


@login_required
def departament_filter(request, departament_pk):
    linked_check = is_linked(request)
    if linked_check:
        return linked_check
    detail = 'Departament'
    workers = get_object_or_404(DepartamentModel, pk=departament_pk).workers()
    return get_items_response(request, workers, detail)


@login_required
def brig_filter(request, brig_pk):
    linked_check = is_linked(request)
    if linked_check:
        return linked_check
    detail = 'Brig'
    workers = WorkerModel.objects.filter(is_active=True, brig_id=brig_pk)
    return get_items_response(request, workers, detail)


@login_required
def worker_filter(request, worker_pk):
    linked_check = is_linked(request)
    if linked_check:
        return linked_check
    detail = 'Worker'
    workers = WorkerModel.objects.filter(is_active=True, pk=worker_pk)
    return get_items_response(request, workers, detail)


def today():
    to_day = datetime.now() + timedelta(hours=5)
    return date(to_day.year, to_day.month, to_day.day)


def is_linked(request):
    if not (request.user.is_linked or request.user.is_superuser):
        messages.warning(request, 'Ваша учётная запись не привязана к работнику! '
                                  'Обратитесь к вашему руководителю или администратору.')
        return HttpResponseRedirect(reverse('main:index'))


def get_items_response(request, workers=None, detail='All', gived_items=None):
    workers = workers if workers else WorkerModel.objects.filter(is_active=True)
    gived_items = gived_items if gived_items else ItemModel.objects.filter(is_active=True,
                                                                           item_type__is_active=True,
                                                                           worker_id__in=workers)
    item_list = ItemTypeModel.objects.filter(is_active=True, group__is_active=True)
    cities = CityModel.objects.filter(is_active=True)
    context = {'page_title': 'список предметов',
               'detail': detail,
               'items': gived_items,
               'item_types': item_list,
               'cities': cities,
               'today': today(),
               }
    return render(request, 'mainapp/items.html', context)


def get_tools():
    pass


def get_docs():
    pass

mainapp/templates/mainapp/departaments.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="flex-grow-1">
        <!--Content top-menu-->
        <ul class="nav shadow-sm">
            <div class="d-flex mt-1 ms-1 mb-1">
                {% include 'mainapp/includes/brig_checker.html' %}
                <li class="nav-item">
                    <a href="#" class="btn btn-outline-primary btn-sm">Запросить</a>
                </li>
            </div>
        </ul>
        <!--/Content top-menu-->
        <p class="ms-3 mt-3 mb-0">
            <a href="departaments.html">г. Нефтекамск</a> > <a href="departaments.html">ООО СВОС</a> >
            <a href="departaments.html">Отдел оптиков-сварщиков</a> > бр. Удинский Дмитрий Игоревич
        </p>
        <div id="layoutSidenav_content">
            <main>
                <div class="container-fluid">
                    <h1 class="">Список сотрудников</h1>
                    <div class="card mb-4 shadow-sm">
                        <div class="card-header">
                            <i class="fas fa-table mr-1"></i> Полный список
                        </div>
                        <div class="card-body">
                            <div class="table-responsive">
                                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                    <thead>
                                    <tr>
                                        <th>Город</th>
                                        <th>Организация</th>
                                        <th>Подразделение</th>
                                        <th>ФИО бригадира</th>
                                        <th>ФИО сотрудника</th>
                                    </tr>
                                    </thead>
                                    <tfoot>
                                    <tr>
                                        <th>Город</th>
                                        <th>Организация</th>
                                        <th>Подразделение</th>
                                        <th>ФИО бригадира</th>
                                        <th>ФИО сотрудника</th>
                                    </tr>
                                    </tfoot>
                                    <tbody>
                                    {% for worker in workers %}
                                        <tr>
                                            <td><a href="city_form.html">
                                                {{ worker.departament.company.city.name }}
                                            </a></td>
                                            <td>
                                                <a href="company_form.html">{{ worker.departament.company.name }}</a>
                                            </td>
                                            <td>
                                                <a href="departament_form.html">{{ worker.departament.name }}</a>
                                            </td>
                                            <td>
                                                <i class="fas fa-bell
                                                {% if worker.brig.brig_status == 3 %}
                                                    text-danger
                                                {% elif worker.brig.brig_status == 2 %}
                                                    text-warning
                                                {% elif worker.brig.brig_status == 1 %}
                                                    text-info
                                                {% else %}
                                                    text-success
                                                {% endif %}
                                                "></i>
                                                <a href="departaments.html">{{ worker.brig.name }}</a>
                                            </td>
                                            <td>
                                                <i class="fas fa-bell
                                                {% if worker.status == 3 %}
                                                    text-danger
                                                {% elif worker.status == 2 %}
                                                    text-warning
                                                {% elif worker.status == 1 %}
                                                    text-info
                                                {% else %}
                                                    text-success
                                                {% endif %}
                                                "></i>
                                                <a href="items.html">{{ worker.name }}</a>
                                            </td>
                                        </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                        <div class="card-footer">
                            <a href="city_form.html" class="btn btn-outline-primary">Добавить город</a>
                            <a href="company_form.html" class="btn btn-outline-primary">Добавить организацию</a>
                            <a href="departament_form.html" class="btn btn-outline-primary">Добавить подразделение</a>
                            <a href="profile.html" class="btn btn-outline-primary">Добавить сотрудника</a>
                        </div>
                    </div>
                </div>
            </main>
        </div>
    </div>
{% endblock %}

mainapp/templates/mainapp/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

{{ block.super }}

    {% if not user.is_authenticated %}
        <div class="alert alert-warning text-center m-1" role="alert">
            Пожалуйста <a href="{% url 'auth:login' %}" class="alert-link">авторизуйтесь</a>!
        </div>
    {% elif user.is_linked %}
        {% if user.linked_worker.status == 2 %}
            <div class="alert alert-warning text-center m-1" role="alert">
                ВНИМАНИЕ! Приближается окончание сроков действия!
            </div>
        {% elif user.linked_worker.status == 3 %}
            <div class="alert alert-danger text-center m-1" role="alert">
                ВНИМАНИЕ! Имеются просрочки!
            </div>
        {% endif %}
    {% endif %}
{% endblock %}

mainapp/templates/mainapp/items.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <!--Content top-menu-->
    <ul class="nav shadow-sm">
        <div class="d-flex mt-1 ms-1 mb-1">
            {% include 'includes/brig_checker.html' %}
            <li class="nav-item dropdown">
                <select class="form-select-sm">
                    <option selected>Тип</option>
                    <option value="1">Инструмент</option>
                    <option value="2">Удостоверение</option>
                </select>
            </li>
            <li class="nav-item dropdown">
                <select class="form-select-sm">
                    <option selected>Наименование</option>
                    {% for item in item_types %}
                        <option value="{{ forloop.counter }}">{{ item.name }}</option>
                    {% endfor %}
                </select>
            </li>
            <li class="nav-item d-flex align-items-center">
                <div class="form-check mx-2">
                    <input class="form-check-input" type="checkbox" value="" id="showAllGroups">
                    <label class="form-check-label" for="showAllGroups">
                        Вся группа
                    </label>
                </div>
            </li>
            <li class="nav-item">
                <a href="AJAX" class="btn btn-outline-primary btn-sm">Запросить</a>
            </li>
        </div>
    </ul>
    <!--/Content top-menu-->

    <!-- Site path -->
    {% if items %}
        <p class="ms-3 mt-3 mb-0">
            {% if detail != 'All' %}
                <a href="{% url 'main:city_filter' items.first.worker.departament.company.city_id %}">
                    {{ items.first.worker.departament.company.city.name }}
                </a>
            {% endif %}
            {% if detail != 'All' and detail != 'City' %}
                >
                <a href="{% url 'main:company_filter' items.first.worker.departament.company_id %}">
                    {{ items.first.worker.departament.company.name }}
                </a>
            {% endif %}
            {% if detail != 'All' and detail != 'City' and detail != 'Company' %}
                >
                <a href="{% url 'main:departament_filter' items.first.worker.departament_id %}">
                    {{ items.first.worker.departament.name }}
                </a>
            {% endif %}
            {% if detail == 'Brig' or detail == 'Worker' %}
                >
                <a href="{% url 'main:brig_filter' items.first.worker.brig_id %}">
                    бр. {{ items.first.worker.brig.name }}
                </a>
            {% endif %}
            {% if detail == 'Worker' %}
                > {{ items.first.worker.name }}
            {% endif %}
        </p>
    {% endif %}
    <!-- /Site path -->

    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid">

                {{ block.super }}

                <h1 class="">Сроки действия инструмента и удостоверений</h1>
                <div class="card mb-4 shadow-sm">
                    <div class="card-header">
                        <i class="fas fa-table mr-1"></i> Полный список
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                <thead>
                                <tr>
                                    <th>Организация</th>
                                    <th>Подразделение</th>
                                    <th>ФИО</th>
                                    <th>Наименование</th>
                                    <th>
                                        <div class="dropdown">
                                            <a class="dropdown-toggle text-reset" href="#" role="button"
                                               id="dropdownMenuLink"
                                               data-bs-toggle="dropdown" aria-expanded="false">
                                                ИН
                                            </a>

                                            <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                                                <li>
                                                    <p class="dropdown-item mb-0">Инвентарный номер</p>
                                                </li>
                                            </ul>
                                        </div>
                                    </th>
                                    <th>Проверка от</th>
                                    <th>Выдача от</th>
                                    <th>Действует до</th>
                                    <th>Сохранить</th>
                                </tr>
                                </thead>
                                <tfoot>
                                <tr>
                                    <th>Организация</th>
                                    <th>Подразделение</th>
                                    <th>ФИО</th>
                                    <th>Наименование</th>
                                    <th>
                                        <div class="dropdown">
                                            <a class="dropdown-toggle text-reset" href="#" role="button"
                                               id="dropdownMenuLink"
                                               data-bs-toggle="dropdown" aria-expanded="false">
                                                ИН
                                            </a>

                                            <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                                                <li>
                                                    <p class="dropdown-item mb-0">Инвентарный номер</p>
                                                </li>
                                            </ul>
                                        </div>
                                    </th>
                                    <th>Проверка от</th>
                                    <th>Выдача от</th>
                                    <th>Действует до</th>
                                    <th>Сохранить</th>
                                </tr>
                                </tfoot>
                                <tbody>

                                {% for el in items %}
                                    <tr class="
                                                {% if el.status == 1 %}
                                                    table-info
                                                {% elif el.status == 2 %}
                                                    table-warning
                                                {% elif el.status == 3 %}
                                                    table-danger
                                                {% endif %}
                                        ">
                                        <td><a href="company_form.html">{{ el.worker.departament.company.name }}</a>
                                        </td>
                                        <td><a href="departament_form.html">{{ el.worker.departament.name }}</a></td>
                                        <td><a href="{% url 'workers:info' el.worker_id %}">{{ el.worker.name }}</a>
                                        </td>
                                        <td>
                                            {% if el.item_type.group.doc_or_tool == 'Удостоверение' %}
                                                <i class="far fa-address-card"></i>
                                            {% else %}
                                                <i class="fas fa-tools"></i>
                                            {% endif %}
                                            <a href="gived_item_details.html">{{ el.item_type.name }}</a>
                                        </td>
                                        <td>{{ el.inventory_number }}</td>
                                        <td class="text-center"><input type="date" class="btn btn-light btn-sm"
                                                                       name="check"
                                                                       value="{{ el.test_for|date:'Y-m-d' }}"
                                        ></td>
                                        <td class="text-center">
                                            {% if el.item_type.group.doc_or_tool == 'Удостоверение' %}
                                                <input type="date" class="btn btn-light btn-sm"
                                                       name="test"
                                                       value="{{ el.change_for|date:'Y-m-d' }}"
                                                >
                                            {% endif %}
                                        </td>
                                        <td class="text-center">
                                            <input type="date" class="btn btn-light btn-sm"
                                                   name="to"
                                                   value="{{ el.elapse|date:'Y-m-d' }}"
                                            >
                                        </td>
                                        <td><a href="#" class="btn btn-secondary btn-sm">Сохранить</a></td>
                                    </tr>
                                {% endfor %}

                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="card-footer">

                    </div>
                </div>
            </div>
        </main>
    </div>
{% endblock %}