authapp/urls.py
from django.urls import path

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('profile/', authapp.profile, name='profile'),
]

datescontrol/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),

    path('', include('mainapp.urls', namespace='main')),
    path('itemtypes/', include('itemtypesapp.urls', namespace='itemtypes')),
    path('workers/', include('workersapp.urls', namespace='workers')),
    path('auth/', include('authapp.urls', namespace='auth')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

itemtypesapp/urls.py
from django.urls import path

import itemtypesapp.views as itemtypes

app_name = 'itemtypesapp'

urlpatterns = [
    path('', itemtypes.item_types, name='index'),
]

mainapp/urls.py
from django.urls import path

import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.index, name='index'),
    path('items/', mainapp.items, name='items'),
    path('items/city_filter/<int:city_pk>/', mainapp.city_filter, name='city_filter'),
    path('items/company_filter/<int:company_pk>/', mainapp.company_filter, name='company_filter'),
    path('items/departament_filter/<int:departament_pk>/', mainapp.departament_filter, name='departament_filter'),
    path('items/brig_filter/<int:brig_pk>/', mainapp.brig_filter, name='brig_filter'),
    path('items/worker_filter/<int:worker_pk>', mainapp.worker_filter, name='worker_filter'),
    path('items/group_filter/<int:item_group_pk>', mainapp.group_filter, name='group_filter'),
    path('items/type_filter/<int:item_type_pk>', mainapp.type_filter, name='type_filter'),
]

itemtypesapp/models.py
from django.db import models


# Create your models here.
class ItemGroupModel(models.Model):
    TOOL = 'Инструмент'
    DOC = 'Удостоверение'
    DOC_OR_TOOL_CHOICES = [
        (TOOL, 'Инструмент'),
        (DOC, 'Удостоверение'),
    ]
    name = models.CharField('Группа предметов', max_length=256)
    description = models.TextField('Примечание', blank=True)
    doc_or_tool = models.CharField('Тип предмета', max_length=64, choices=DOC_OR_TOOL_CHOICES)
    photo = models.ImageField('Фото', upload_to='item_group_images', blank=True)
    is_active = models.BooleanField('Активен', default=True)

    def __str__(self):
        return f'{self.name} ({self.doc_or_tool})'

    class Meta:
        verbose_name = 'Группа предметов'
        verbose_name_plural = 'Группы предметов'
        ordering = ['name']


class ItemTypeModel(models.Model):
    group = models.ForeignKey(ItemGroupModel, on_delete=models.CASCADE)
    name = models.CharField('Имя предмета', max_length=256)
    description = models.TextField('Примечание', blank=True)
    photo = models.ImageField('Фото', upload_to='item_images', blank=True)
    change_interval = models.SmallIntegerField('Интервал выдачи', default=12)
    test_interval = models.SmallIntegerField('Интервал проверки', default=12)
    is_active = models.BooleanField('Активен', default=True)

    def __str__(self):
        return f'{self.name} ({self.group.doc_or_tool})'

    class Meta:
        verbose_name = 'Тип предмета'
        verbose_name_plural = 'Типы предметов'
        ordering = ['name']

itemtypesapp/views.py
from datetime import date, timedelta, datetime

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from itemtypesapp.models import ItemTypeModel


@login_required
def item_types(request):
    if not (request.user.is_linked or request.user.is_superuser):
        messages.warning(request, 'Ваша учётная запись не привязана к работнику! '
                                  'Обратитесь к вашему руководителю или администратору.')
        return HttpResponseRedirect(reverse('main:index'))
    docs = ItemTypeModel.objects.filter(is_active=True, group__doc_or_tool='Удостоверение')
    tools = ItemTypeModel.objects.filter(is_active=True, group__doc_or_tool='Инструмент')
    context = {'page_title': 'типы предметов',
               'docs': docs,
               'tools': tools,
               'today': today(),
               }
    return render(request, 'itemtypesapp/item_types.html', context)


def today():
    to_day = datetime.now() + timedelta(hours=5)
    return date(to_day.year, to_day.month, to_day.day)

itemtypesapp/templates/itemtypesapp/item_types.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid">

{{ block.super }}

                <h1 class="">Виды инструмента и удостоверений</h1>
                <!-- Tab menu -->
                <ul class="nav nav-tabs" id="myTab" role="tablist">
                    <li class="nav-item" role="presentation">
                        <button class="nav-link active" id="home-tab" data-bs-toggle="tab" data-bs-target="#home"
                                type="button" role="tab" aria-controls="home" aria-selected="true">Удостоверения
                        </button>
                    </li>
                    <li class="nav-item" role="presentation">
                        <button class="nav-link" id="profile-tab" data-bs-toggle="tab" data-bs-target="#profile"
                                type="button"
                                role="tab" aria-controls="profile" aria-selected="false">Инструмент
                        </button>
                    </li>
                </ul>
                <!-- /Tab menu -->
                <div class="tab-content" id="myTabContent">
                    <!-- Documents tab -->
                    <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                        <div class="card mb-4 shadow-sm">
                            <div class="card-header">
                                <i class="fas fa-table mr-1"></i> Виды удостоверений
                            </div>
                            <div class="card-body">
                                <div class="table-responsive">
                                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                        <thead>
                                        <tr>
                                            <th>Тип удостоверений</th>
                                            <th>Наименование</th>
                                            <th>Интервал аттестаций</th>
                                            <th>Интервал замены</th>
                                            <th>Перейти к выданным удостоверениям</th>
                                        </tr>
                                        </thead>
                                        <tfoot>
                                        <tr>
                                            <th>Тип удостоверений</th>
                                            <th>Наименование</th>
                                            <th>Интервал аттестаций</th>
                                            <th>Интервал замены</th>
                                            <th>Перейти к выданным удостоверениям</th>
                                        </tr>
                                        </tfoot>
                                        <tbody>
                                        {% for el in docs %}
                                            <tr>
                                                <td><a href="item_group_details.html">{{ el.group.name }}</a></td>
                                                <td><a href="item_type_details.html">{{ el.name }}</a></td>
                                                <td>{{ el.test_interval }}</td>
                                                <td>{{ el.change_interval }}</td>
                                                <td>
                                                    <a href="{% url 'main:group_filter' el.group_id %}"
                                                       class="btn btn-secondary btn-sm"
                                                    >
                                                        Этот тип удостоверений
                                                    </a>
                                                    <a href="{% url 'main:type_filter' el.id %}"
                                                       class="btn btn-secondary btn-sm"
                                                    >
                                                        Это наименование
                                                    </a>
                                                </td>
                                            </tr>
                                        {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                            <div class="card-footer">
                                <a href="item_group_details.html" class="btn btn-outline-primary btn-block">Добавить
                                    группу</a>
                                <a href="item_type_details.html" class="btn btn-outline-primary btn-block">Добавить
                                    тип
                                    предмета</a>
                            </div>
                        </div>
                    </div>
                    <!-- Tools Tab -->
                    <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
                        <div class="card mb-4 shadow-sm">
                            <div class="card-header">
                                <i class="fas fa-table mr-1"></i> Виды инструмента
                            </div>
                            <div class="card-body">
                                <div class="table-responsive">
                                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                        <thead>
                                        <tr>
                                            <th>Группа инструмента</th>
                                            <th>Наименование</th>
                                            <th>Интервал проверки</th>
                                            <th>Перейти к выданному инструменту</th>
                                        </tr>
                                        </thead>
                                        <tfoot>
                                        <tr>
                                            <th>Группа инструмента</th>
                                            <th>Наименование</th>
                                            <th>Интервал проверки</th>
                                            <th>Перейти к выданному инструменту</th>
                                        </tr>
                                        </tfoot>
                                        <tbody>
                                        {% for el in tools %}
                                            <tr>
                                                <td><a href="item_group_details.html">{{ el.group.name }}</a></td>
                                                <td><a href="item_type_details.html">{{ el.name }}</a></td>
                                                <td>{{ el.test_interval }}</td>
                                                <td>
                                                    <a href="{% url 'main:group_filter' el.group_id %}"
                                                       class="btn btn-secondary btn-sm"
                                                    >
                                                        Эта группа инструмента
                                                    </a>
                                                    <a href="{% url 'main:type_filter' el.id %}"
                                                       class="btn btn-secondary btn-sm"
                                                    >
                                                        Это наименование
                                                    </a>
                                                </td>
                                            </tr>
                                        {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                            <div class="card-footer">
                                <a href="item_group_details.html" class="btn btn-outline-primary btn-block">Добавить
                                    группу</a>
                                <a href="item_type_details.html" class="btn btn-outline-primary btn-block">Добавить
                                    тип
                                    предмета</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </main>
    </div>
{% endblock %}