authapp/urls.py
from django.urls import path

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('profile/', authapp.profile, name='profile'),
]

datescontrol/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),

    path('', include('mainapp.urls', namespace='main')),
    path('itemtypes/', include('itemtypesapp.urls', namespace='itemtypes')),
    path('workers/', include('workersapp.urls', namespace='workers')),
    path('auth/', include('authapp.urls', namespace='auth')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path

import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.index, name='index'),
    path('items/', mainapp.items, name='items'),
    path('items/city_filter/<int:city_pk>/', mainapp.city_filter, name='city_filter'),
    path('items/company_filter/<int:company_pk>/', mainapp.company_filter, name='company_filter'),
    path('items/departament_filter/<int:departament_pk>/', mainapp.departament_filter, name='departament_filter'),
    path('items/brig_filter/<int:brig_pk>/', mainapp.brig_filter, name='brig_filter'),
    path('items/worker_filter/<int:worker_pk>', mainapp.worker_filter, name='worker_filter'),
    path('items/group_filter/<int:item_group_pk>', mainapp.group_filter, name='group_filter'),
    path('items/type_filter/<int:item_type_pk>', mainapp.type_filter, name='type_filter'),
]

workersapp/urls.py
from django.urls import path

import workersapp.views as workersapp

app_name = 'workersapp'

urlpatterns = [
    path('', workersapp.workers, name='index'),
    path('city_filter/<int:city_pk>/', workersapp.city_filter, name='city_filter'),
    path('company_filter/<int:company_pk>/', workersapp.company_filter, name='company_filter'),
    path('departament_filter/<int:departament_pk>/', workersapp.departament_filter, name='departament_filter'),
    path('brig_filter/<int:brig_pk>/', workersapp.brig_filter, name='brig_filter'),
    path('info/<int:pk>/', workersapp.info, name='info'),
]

workersapp/models.py
from django.contrib.auth import get_user_model
from django.db import models


class CityModel(models.Model):
    name = models.CharField('Филиал', max_length=256)
    description = models.TextField('Примечание', blank=True)
    photo = models.ImageField('Фото', upload_to='city_images', blank=True)
    is_active = models.BooleanField('Активен', default=True)

    def __str__(self):
        return f'{self.name}'

    def workers(self, brig_only=False):
        companies = self.companymodel_set.filter(is_active=True)
        departaments = DepartamentModel.objects.filter(company__in=companies, is_active=True)
        return WorkerModel.objects.filter(departament__in=departaments, is_brig=True, is_active=True) \
            if brig_only \
            else WorkerModel.objects.filter(departament__in=departaments, is_active=True)

    class Meta:
        verbose_name = 'Филиал'
        verbose_name_plural = 'Филиалы'
        ordering = ['name']


class CompanyModel(models.Model):
    city = models.ForeignKey(CityModel, on_delete=models.CASCADE)
    name = models.CharField('Организация', max_length=256)
    description = models.TextField('Примечание', blank=True)
    photo = models.ImageField('Фото', upload_to='company_images', blank=True)
    is_active = models.BooleanField('Активен', default=True)

    def __str__(self):
        return f'{self.name} ({self.city.name})'

    def workers(self, brig_only=False):
        departaments = self.departamentmodel_set.filter(is_active=True)
        return WorkerModel.objects.filter(departament__in=departaments, is_brig=True, is_active=True) \
            if brig_only \
            else WorkerModel.objects.filter(departament__in=departaments, is_active=True)

    class Meta:
        verbose_name = 'Организация'
        verbose_name_plural = 'Организации'
        ordering = ['name']


class DepartamentModel(models.Model):
    company = models.ForeignKey(CompanyModel, on_delete=models.CASCADE)
    name = models.CharField('Подразделение', max_length=256)
    description = models.TextField('Примечание', blank=True)
    photo = models.ImageField('Фото', upload_to='departament_images', blank=True)
    is_active = models.BooleanField('Активен', default=True)

    def __str__(self):
        return f'{self.name} ({self.company.name}-{self.company.city.name})'

    def workers(self, brig_only=False):
        return self.workermodel_set.filter(is_brig=True, is_active=True) \
            if brig_only \
            else self.workermodel_set.filter(is_active=True)

    class Meta:
        verbose_name = 'Подразделение'
        verbose_name_plural = 'Подразделения'
        ordering = ['name']


class WorkerModel(models.Model):
    departament = models.ForeignKey(DepartamentModel, on_delete=models.CASCADE)
    linked_user = models.ForeignKey(get_user_model(),
                                    on_delete=models.SET_NULL,
                                    blank=True, null=True)
    brig = models.ForeignKey('self',
                             on_delete=models.PROTECT,
                             limit_choices_to={'is_brig': True},
                             blank=True, null=True)
    name = models.CharField('ФИО сотрудника', max_length=256)
    number = models.IntegerField('Табельный номер', default=0)
    description = models.TextField('Примечание', blank=True)
    is_brig = models.BooleanField('Бригадир', default=False)
    is_company_leader = models.BooleanField('Руководитель орг.', default=False)
    is_departament_leader = models.BooleanField('Руководитель подр.', default=False)
    is_active = models.BooleanField('Активен', default=True)

    def __str__(self):
        return f'{self.name} ({self.departament.name}-{self.departament.company.city.name})'

    @property
    def status(self):
        items = self.itemmodel_set.filter(is_active=True)
        result = 0
        for item in items:
            status = item.status
            if status > result:
                result = status
                if result == 3:
                    break
        return result

    @property
    def brig_status(self):
        if self.is_brig:
            workers = self.workermodel_set.filter(is_active=True)
            result = 0
            for worker in workers:
                status = worker.status
                if status > result:
                    result = status
                    if result == 3:
                        break
            return result
        return 0

    @property
    def tools(self):
        tools_set = self.itemmodel_set.filter(item_type__group__doc_or_tool='Инструмент', is_active=True)
        return sorted(tools_set, reverse=True, key=lambda itm: itm.status)

    @property
    def docs(self):
        docs_set = self.itemmodel_set.filter(item_type__group__doc_or_tool='Удостоверение', is_active=True)
        return sorted(docs_set, reverse=True, key=lambda itm: itm.status)

    class Meta:
        verbose_name = 'Сотрудник'
        verbose_name_plural = 'Сотрудники'
        ordering = ['name']

workersapp/views.py
from datetime import date, timedelta, datetime

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse

from workersapp.models import CityModel, CompanyModel, DepartamentModel, WorkerModel
from mainapp.views import is_linked, today


@login_required
def workers(request):
    linked_check = is_linked(request)
    if linked_check:
        return linked_check
    worker_list = WorkerModel.objects.filter(is_active=True, is_brig=True) \
        .order_by('departament__company__city__name', 'departament__company__name', 'departament__name', 'name')
    return get_workers_response(request, worker_list)


@login_required
def city_filter(request, city_pk):
    linked_check = is_linked(request)
    if linked_check:
        return linked_check
    detail = 'City'
    worker_list = get_object_or_404(CityModel, pk=city_pk).workers(brig_only=True) \
        .order_by('departament__company__name', 'departament__name', 'name')
    return get_workers_response(request, worker_list, detail)


@login_required
def company_filter(request, company_pk):
    linked_check = is_linked(request)
    if linked_check:
        return linked_check
    detail = 'Company'
    worker_list = get_object_or_404(CompanyModel, pk=company_pk).workers(brig_only=True) \
        .order_by('departament__name', 'name')
    return get_workers_response(request, worker_list, detail)


@login_required
def departament_filter(request, departament_pk):
    linked_check = is_linked(request)
    if linked_check:
        return linked_check
    detail = 'Departament'
    worker_list = get_object_or_404(DepartamentModel, pk=departament_pk).workers() \
        .order_by('brig__name', 'name')
    return get_workers_response(request, worker_list, detail)


@login_required
def brig_filter(request, brig_pk):
    linked_check = is_linked(request)
    if linked_check:
        return linked_check
    detail = 'Brig'
    worker_list = WorkerModel.objects.filter(brig_id=brig_pk).order_by('name')
    return get_workers_response(request, worker_list, detail)


@login_required
def info(request, pk):
    linked_check = is_linked(request)
    if linked_check:
        return linked_check
    worker = get_object_or_404(WorkerModel, pk=pk)
    context = {'page_title': 'Подробности о сотруднике',
               'worker': worker,
               'today': today(),
               'rules': rules(request.user, worker)
               }
    return render(request, 'workersapp/worker_info.html', context)


def get_lists(city_pk, company_pk, departament_pk):
    brigadier_list = WorkerModel.objects.filter(is_brig=True,
                                                is_active=True,
                                                departament_id=departament_pk) if departament_pk else None
    departament_list = DepartamentModel.objects.filter(is_active=True, company_id=company_pk) if company_pk else None
    company_list = CompanyModel.objects.filter(is_active=True, city_id=city_pk) if city_pk else None
    city_list = CityModel.objects.filter(is_active=True)
    return {
        'brigadier_list': brigadier_list,
        'departament_list': departament_list,
        'company_list': company_list,
        'city_list': city_list,
    }


def get_workers_response(request, worker_list, detail='All'):
    cities = CityModel.objects.filter(is_active=True)
    context = {'page_title': 'список сотрудников',
               'workers': worker_list,
               'detail': detail,
               'cities': cities,
               'today': today(),
               }
    return render(request, 'workersapp/workers.html', context)


def rules(user, worker):
    u_worker = user.linked_worker
    if u_worker:
        return departaments_rules(u_worker, worker) or departaments_rules(u_worker, worker)


def departaments_rules(checked_worker, worker):
    if checked_worker.is_departament_leader:
        return checked_worker.departament == worker.departament


def company_rules(checked_worker, worker):
    if checked_worker.is_departament_leader:
        return checked_worker.departament == worker.departament

workersapp/templates/workersapp/workers.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <!--Content top-menu AJAX -->
    <ul class="nav shadow-sm">
        <div class="d-flex mt-1 ms-1 mb-1">
            {% include 'includes/brig_checker.html' %}
            <li class="nav-item">
                <a href="AJAX" class="btn btn-outline-primary btn-sm">Запросить</a>
            </li>
        </div>
    </ul>
    <!--/Content top-menu-->

    <!-- Site path -->
    {% if workers %}
        <p class="ms-3 mt-3 mb-0">
            {% if detail != 'All' %}
                <a href="{% url 'workersapp:city_filter' workers.first.departament.company.city_id %}">
                    {{ workers.first.departament.company.city.name }}
                </a>
            {% endif %}
            {% if detail != 'All' and detail != 'City' %}
                >
                <a href="{% url 'workersapp:company_filter' workers.first.departament.company_id %}">
                    {{ workers.first.departament.company.name }}
                </a>
            {% endif %}
            {% if detail == 'Departament' or detail == 'Brig' %}
                >
                <a href="{% url 'workersapp:departament_filter' workers.first.departament_id %}">
                    {{ workers.first.departament.name }}
                </a>
            {% endif %}
            {% if detail == 'Brig' %}
                > бр. {{ workers.first.brig.name }}
            {% endif %}
        </p>
    {% endif %}
    <!-- /Site path -->

    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid">

                {{ block.super }}

                <h1 class="">Список сотрудников</h1>
                <div class="card mb-4 shadow-sm">
                    <div class="card-header">
                        <i class="fas fa-table mr-1"></i> Полный список
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                <thead>
                                <tr>
                                    {% if detail != 'Brig' and detail != 'Departament' %}
                                        <th>Город</th>
                                    {% endif %}
                                    <th>Организация</th>
                                    <th>Подразделение</th>
                                    <th>ФИО бригадира</th>
                                    {% if detail == 'Brig' or detail == 'Departament' %}
                                        <th>ФИО сотрудника</th>
                                    {% endif %}
                                </tr>
                                </thead>
                                <tfoot>
                                <tr>
                                    {% if detail != 'Brig' and detail != 'Departament' %}
                                        <th>Город</th>
                                    {% endif %}
                                    <th>Организация</th>
                                    <th>Подразделение</th>
                                    <th>ФИО бригадира</th>
                                    {% if detail == 'Brig' or detail == 'Departament' %}
                                        <th>ФИО сотрудника</th>
                                    {% endif %}
                                </tr>
                                </tfoot>
                                <tbody>
                                {% for worker in workers %}
                                    <tr>
                                        {% if detail != 'Brig' and detail != 'Departament' %}
                                            <td><a href="city_form.html">
                                                {{ worker.departament.company.city.name }}
                                            </a></td>
                                        {% endif %}
                                        <td>
                                            <a href="company_form.html">{{ worker.departament.company.name }}</a>
                                        </td>
                                        <td>
                                            <a href="departament_form.html">{{ worker.departament.name }}</a>
                                        </td>
                                        <td>
                                            <i class="fas fa-bell
                                                {% if worker.brig.brig_status == 3 %}
                                                    text-danger
                                                {% elif worker.brig.brig_status == 2 %}
                                                    text-warning
                                                {% elif worker.brig.brig_status == 1 %}
                                                    text-info
                                                {% else %}
                                                    text-success
                                                {% endif %}
                                                "></i>
                                            <a href="{% url 'workers:brig_filter' worker.brig_id %}">
                                                {{ worker.brig.name }}
                                            </a>
                                        </td>
                                        {% if detail == 'Brig' or detail == 'Departament' %}
                                            <td>
                                                <i class="fas fa-bell
                                                {% if worker.status == 3 %}
                                                    text-danger
                                                {% elif worker.status == 2 %}
                                                    text-warning
                                                {% elif worker.status == 1 %}
                                                    text-info
                                                {% else %}
                                                    text-success
                                                {% endif %}
                                                "></i>
                                                <a href="{% url 'main:worker_filter' worker.pk %}">
                                                    {{ worker.name }}
                                                </a>
                                            </td>
                                        {% endif %}
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="card-footer">
                        <a href="city_form.html" class="btn btn-outline-primary">Добавить город</a>
                        <a href="company_form.html" class="btn btn-outline-primary">Добавить организацию</a>
                        <a href="departament_form.html" class="btn btn-outline-primary">Добавить подразделение</a>
                        <a href="profile.html" class="btn btn-outline-primary">Добавить сотрудника</a>
                    </div>
                </div>
            </div>
        </main>
    </div>
{% endblock %}