authapp/urls.py
from django.urls import path

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('profile/', authapp.profile, name='profile'),
]

datescontrol/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),

    path('', include('mainapp.urls', namespace='main')),
    path('itemtypes/', include('itemtypesapp.urls', namespace='itemtypes')),
    path('workers/', include('workersapp.urls', namespace='workers')),
    path('auth/', include('authapp.urls', namespace='auth')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path

import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.index, name='index'),
    path('items/', mainapp.items, name='items'),
    path('items/city_filter/<int:city_pk>/', mainapp.city_filter, name='city_filter'),
    path('items/company_filter/<int:company_pk>/', mainapp.company_filter, name='company_filter'),
    path('items/departament_filter/<int:departament_pk>/', mainapp.departament_filter, name='departament_filter'),
    path('items/brig_filter/<int:brig_pk>/', mainapp.brig_filter, name='brig_filter'),
    path('items/worker_filter/<int:worker_pk>', mainapp.worker_filter, name='worker_filter'),
    path('items/group_filter/<int:item_group_pk>', mainapp.group_filter, name='group_filter'),
    path('items/type_filter/<int:item_type_pk>', mainapp.type_filter, name='type_filter'),
]

workersapp/urls.py
from django.urls import path

import workersapp.views as workersapp

app_name = 'workersapp'

urlpatterns = [
    path('', workersapp.workers, name='index'),
    path('city_filter/<int:city_pk>/', workersapp.city_filter, name='city_filter'),
    path('company_filter/<int:company_pk>/', workersapp.company_filter, name='company_filter'),
    path('departament_filter/<int:departament_pk>/', workersapp.departament_filter, name='departament_filter'),
    path('brig_filter/<int:brig_pk>/', workersapp.brig_filter, name='brig_filter'),
    path('info/<int:pk>/', workersapp.info, name='info'),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Аудит дат. {{ page_title|capfirst }}</title>

    {% block css %}
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
        <link href="{% static 'css/all.css' %}" rel="stylesheet">
    {% endblock %}

</head>

<body class="wrapper">
<div class="top">
    <!-- Top menu-->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a href="#" class="show-hide-sidemenu navbar-brand"><i class="fas fa-bars"></i></a>
            <a class="navbar-brand" href="{% url 'main:index' %}">Экзамены, аттестации,
                инструмент {{ today|date:'d.m.Y' }}</a>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="nav nav-pills ms-auto">

                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link userprofile text-body"
                               href="
                                    {% if user.is_linked %}
                                        {% url 'workers:info' user.linked_worker.pk %}
                                    {% else %}
                                        {% url 'auth:profile' %}
                                    {% endif %}
                               "
                            >
                                <i class="fas fa-user-circle"></i>
                                <i class="fas fa-bell text-warning"></i>
                                {{ user.username|title }}
                            </a>
                        </li>

                        {% if user.is_superuser %}
                            <li class="nav-item">
                                <a class="nav-link text-body" href="/">
                                    <i class="fas fa-users-cog"></i>
                                    Управление
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-body" href="/admin">
                                    <i class="fas fa-users-cog"></i>
                                    встроенная админка
                                </a>
                            </li>
                        {% endif %}

                        <li class="nav-item">
                            <a class="nav-link text-danger" href="{% url 'auth:logout' %}">
                                Выйти
                                <i class="fas fa-sign-out-alt"></i>
                            </a>
                        </li>

                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link text-body" href="{% url 'auth:login' %}">
                                <i class="fas fa-sign-in-alt"></i>
                                Войти
                            </a>
                        </li>
                    {% endif %}

                </ul>
                <form class="d-flex">
                    <input class="form-control me-2" type="search" placeholder="Фамилия" aria-label="Search">
                    <button class="btn btn-outline-secondary" type="submit"><i class="fas fa-search"></i></button>
                </form>
            </div>
        </div>
    </nav>
    <!--/Top menu-->
    <div class="d-flex page-content">
        <!-- Side menu-->
        <div class="sidemenu">
            <div class="list-group shadow-sm">
                <h2 class="list-group-item mb-0">Списки</h2>
                {% if user.is_authenticated %}
                    <a href="{% url 'workers:index' %}" class="list-group-item
                    {% if page_title == 'список сотрудников' %}
                    active
                    {% endif %}
                    ">
                        Сотрудники
                    </a>
                    <a href="{% url 'main:items' %}" class="list-group-item
                {% if page_title == 'список предметов' %}
                active
                {% endif %}
                ">
                        Предметы
                    </a>
                    <a href="{% url 'itemtypes:index' %}" class="list-group-item
                {% if page_title == 'типы предметов' %}
                active
                {% endif %}
                ">
                        Виды&nbspпредметов
                    </a>
                {% else %}
                    <a href="{% url 'auth:login' %}" class="list-group-item">
                        Авторизуйтесь
                    </a>
                {% endif %}
            </div>
        </div>
        <!--/Side menu-->

        <!-- Content -->
        <div class="flex-grow-1">
            {% block content %}
                {% if messages %}
                    <div class="flex-grow-1">
                        {% for message in messages %}
                            <div class="alert alert-{{ message.tags }} text-center m-1" role="alert">
                                <button type="button"
                                        class="btn-close float-right"
                                        data-bs-dismiss="alert"
                                        aria-label="Close">
                                </button>
                                <p class="m-0">{{ message }}</p>
                            </div>
                        {% endfor %}
                    </div>
                {% endif %}
            {% endblock %}
        </div>
        <!--/Content -->
    </div>
</div>
<footer class="py-4 bg-light mt-auto">
    <div class="container-fluid">
        <div class="d-flex align-items-center justify-content-between small">
            <div class="text-muted">Copyright &copy; Удинский Дмитрий 2021</div>
        </div>
    </div>
</footer>

{% block js %}
    <script src="{% static 'js/fontawesome-icons.js' %}"></script>
    <script src="{% static 'js/jquery-3.6.0.slim.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/burger.js' %}"></script>
{% endblock %}


</body>

</html>